# Generated by Django 4.1.4 on 2022-12-17 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_cartitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
