# Generated by Django 4.1.4 on 2022-12-17 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_orders_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='is_paid',
        ),
    ]
