# Generated by Django 4.1.4 on 2022-12-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.CharField(blank=True, default='Ecom', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='company_mail',
            field=models.CharField(blank=True, default='Ecom@gmail.com', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='web',
            field=models.CharField(blank=True, default='Ecom.com', max_length=255, null=True),
        ),
    ]
