# Generated by Django 4.1.4 on 2022-12-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='added_by',
            field=models.CharField(default='Ecom', max_length=255),
        ),
    ]
